### ISSUE TITLE
KeyError: 'lead_image_url'

### ISSUE THREAD

**Issue by Mavrikant** [mr-karan/webkin#2]
I'm getting this error.

```
user@mavrikant:~$ sudo webkin -u=https://medium.com/@mrkaran/my-development-setup-7e767d33fc41 --verbose
DEBUG: 2017-11-17 14:11:42,568 - parse_url - Parsing https://medium.com/@mrkaran/my-development-setup-7e767d33fc41
Traceback (most recent call last):
  File "/usr/local/bin/webkin", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/webkin/webkin.py", line 34, in main
    parse_url(url=args.url)
  File "/usr/local/lib/python3.5/dist-packages/webkin/webkin.py", line 52, in parse_url
    return convert_html(data, directory)
  File "/usr/local/lib/python3.5/dist-packages/webkin/webkin.py", line 68, in convert_html
    if data['lead_image_url'] is not None:
KeyError: 'lead_image_url'

```

**Comment by Mavrikant** [comment]
Nevermind Its working now.

**Comment by NightMachinery** [comment]
I’m getting this error, too:
```webkin -u https://www.wuxiaworld.com/novel/renegade-immortal/rge-chapter-1298
Traceback (most recent call last):
  File "/home/eva/anaconda/bin/webkin", line 11, in <module>
    sys.exit(main())
  File "/home/eva/anaconda/lib/python3.7/site-packages/webkin/webkin.py", line 34, in main
    parse_url(url=args.url)
  File "/home/eva/anaconda/lib/python3.7/site-packages/webkin/webkin.py", line 52, in parse_url
    return convert_html(data, directory)
  File "/home/eva/anaconda/lib/python3.7/site-packages/webkin/webkin.py", line 68, in convert_html
    if data['lead_image_url'] is not None:
KeyError: 'lead_image_url'
```
